// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthResponse struct {
	Message             string  `json:"message"`
	ShouldShowOtpScreen *bool   `json:"should_show_otp_screen"`
	AccessToken         *string `json:"access_token"`
	IDToken             *string `json:"id_token"`
	RefreshToken        *string `json:"refresh_token"`
	ExpiresIn           *int64  `json:"expires_in"`
	User                *User   `json:"user"`
}

type Env struct {
	DatabaseURL       *string  `json:"DATABASE_URL"`
	DatabaseName      *string  `json:"DATABASE_NAME"`
	DatabaseNamespace *string  `json:"DATABASE_NAMESPACE"`
	DatabaseUsername  *string  `json:"DATABASE_USERNAME"`
	Port              *string  `json:"PORT"`
	JwtType           *string  `json:"JWT_TYPE"`
	JwtSecret         *string  `json:"JWT_SECRET"`
	JwtPrivateKey     *string  `json:"JWT_PRIVATE_KEY"`
	JwtPublicKey      *string  `json:"JWT_PUBLIC_KEY"`
	ClientID          *string  `json:"CLIENT_ID"`
	Roles             []string `json:"ROLES"`
	DefaultRoles      []string `json:"DEFAULT_ROLES"`
}

type Response struct {
	Message string `json:"message"`
}

type SignUpInput struct {
	Email                    string   `json:"email"`
	Password                 string   `json:"password"`
	ConfirmPassword          string   `json:"confirm_password"`
	UserName                 *string  `json:"user_name"`
	FamilyName               *string  `json:"family_name"`
	GivenName                *string  `json:"given_name"`
	MiddleName               *string  `json:"middle_name"`
	Nickname                 *string  `json:"nickname"`
	Gender                   *string  `json:"gender"`
	BirthDate                *string  `json:"birth_date"`
	PhoneNumber              *string  `json:"phone_number"`
	Picture                  *string  `json:"picture"`
	Roles                    []string `json:"roles"`
	RedirectURI              *string  `json:"redirect_uri"`
	IsMultiFactorAuthEnabled *bool    `json:"is_multi_factor_auth_enabled"`
}

type UpdateEnvInput struct {
	JwtType      *string  `json:"JWT_TYPE"`
	JwtSecret    *string  `json:"JWT_SECRET"`
	ClientID     *string  `json:"CLIENT_ID"`
	Roles        []string `json:"ROLES"`
	DefaultRoles []string `json:"DEFAULT_ROLES"`
}

type User struct {
	ID                       string   `json:"id"`
	Email                    string   `json:"email"`
	EmailVerified            bool     `json:"email_verified"`
	SignupMethods            string   `json:"signup_methods"`
	UserName                 *string  `json:"user_name"`
	FamilyName               *string  `json:"family_name"`
	GivenName                *string  `json:"given_name"`
	MiddleName               *string  `json:"middle_name"`
	Nickname                 *string  `json:"nickname"`
	Gender                   *string  `json:"gender"`
	BirthDate                *string  `json:"birth_date"`
	PhoneNumber              *string  `json:"phone_number"`
	PhoneNumberVerified      *bool    `json:"phone_number_verified"`
	Picture                  *string  `json:"picture"`
	Roles                    []string `json:"roles"`
	CreatedAt                *int64   `json:"created_at"`
	UpdatedAt                *int64   `json:"updated_at"`
	RevokedTimestamp         *int64   `json:"revoked_timestamp"`
	IsMultiFactorAuthEnabled *bool    `json:"is_multi_factor_auth_enabled"`
}
