// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Env struct {
	DatabaseURL string `json:"DATABASE_URL"`
	RedisURL    string `json:"REDIS_URL"`
}

type UpdateEnv struct {
	DatabaseURL string `json:"DATABASE_URL"`
	RedisURL    string `json:"REDIS_URL"`
}
